### ISSUE TITLE
Current list of Broken URLs

### ISSUE THREAD

**Issue by TekkyNeko** [vrchivejson/vrchivejson.github.io#26]
I'm going to use this issue to list all broken links i find. if i find more i will update this issue
### Avatars:
[YuYue's Model - Osko](https://anonfiles.com/G4OdTf3fzc/Osko_zip)
[Ayanami](https://anonfiles.com/O0s1S8A8y0/034_-_Ayanami_zip)
[AZAMI](https://linkmix.co/16583816) AnonFiles in LinkMix
[Sophina - v1.2.0](https://linkmix.co/16655697) AnonFiles in LinkMix, the other URLs work
[Summer for U - v1.2](https://linkmix.co/16655781) AnonFiles in LinkMix, the other URLs work
[Kuraimu - v2.01](https://linkmix.co/16655902) AnonFiles in LinkMix, the other URLs work
[Meiyun - v2.0.1](https://linkmix.co/17046129) AnonFiles in LinkMix, the other URLs work
[Rushina v1.22](https://linkmix.co/17625491) AnonFiles in LinkMix, the other URLs work
[suzuhana](https://drive.google.com/file/d/1d4G8t3mM1TF7b3_5MZWHRXbwcOSQVE0-/view?usp=sharing) taken down due to ToS on GDrive
[Rusk](https://booth.pximg.net/61a3b2d7-b4b1-4f97-9e48-ffe959b26ae9/i/2559783/28f1cc6b-16aa-446f-947d-fb10f48bb250_base_resized.jpg) Literally takes you to the image used, Rusk - v1.21 works fine
[Mona](https://drive.google.com/file/d/1qqnKsZ7aEY4RNYfuDaPBawzBf50zXlh7/view) not the R-18 ver
[Ukon second type Ver.1.10](https://workupload.com/file/AunJGDMMnV9) just remove, 4 versions of Ukon 2nd on site anyways
[Adaptive beast Experimental subject β](https://mega.nz/file/g6ElULQZ#sK7x47qLaXvpKhu3AsXIMmBL4UVCRXCOrhkMUSREZ2g)
[Mellcul](https://mega.nz/file/oyk2UY5b#fWUOgdgzwZXkTDmc7fEnTIHnX5McLjLQsdNxhEaR16E)

in premium_furry_base.json:
[MANGA Poppi](https://anonfiles.com/uaY4Ffx7zf/VRCMangaPoppiV1_02_1_zip) 
[Hyenid (v 1.16)](https://drive.google.com/file/d/1EVL3VwE5rkNLsdidSqLofkbFqjugS7Er/view)
[Hobkin Redux](https://drive.google.com/file/d/1_3oFa6pdWAZQmDIRqYBZzprVP4MYU7HQ/view?usp=share_link)
[Baller Fox](https://mega.nz/file/BYRXCLIC#H5neRceBGBdYBYRWSaDnza-lb7ZCRKn1u8xjm-58pi4)

### Clothing:
[Runa Machine Learning Outfit](https://anonfiles.com/zdqbYfo1zb/torinyanruna_mloutfit_1_1_unitypackage) (note this asset is also duped in the website)
[Runa Lazy Devil Set](https://anonfiles.com/Zbi9D6p5z9/Runa_Lazy_Devil_v1_0_unitypackage) 
[RUNA/LUNA Long Dress](https://mega.nz/file/UlYghSbS#JqVYY9SpIu9oIgBloK-qGLM31-A9O4MhjK7PBbZOpvI) Remove the mega.nz listing cause a newer workupload one already is on the site
[Tetsuko B0-0BA Attachment Pack](https://drive.google.com/file/d/1ZZ29aP0xtz8rO6cW5uoFYpUJgrCS-daQ/view?usp=sharing)
[Tetsuko's Oni Mask](https://drive.google.com/file/d/1oEn12qN1beTdk4urqgM4ZkhwxbjDdJJb/view?usp=sharing)
[Chloe dress](https://drive.google.com/file/d/184TM79_sfzxUx7Y1zJ8riq8j7PvmhCAn/view?usp=sharing) Taken down due to GDrive ToS
[SUMMER UNIFORM](https://www.mediafire.com/error.php?errno=320&origin=download)
[Scarlett : Cat under the moonlight](https://mega.nz/file/UlYghSbS#JqVYY9SpIu9oIgBloK-qGLM31-A9O4MhjK7PBbZOpvI)
[Marshmallow Winter for Kikyo](https://workupload.com/file/8LqfsAgb5m9)
[angel worker suit](https://linkmix.co/16775517) AnonFiles in LinkMix, the other URL works
[Tech-Optimal](https://workupload.com/file/xUytNktBFQV)
[Rayna](https://workupload.com/file/5Ws3f6qazqb)

### Assets:
[[For Kikyo] High Cut Sneakers](https://anonfiles.com/ree3wcqdz4/Kikyo_Sneakers_Ver1_00_zip)
[sports sandals for Kikyo](https://anonfiles.com/9di1wcqfz7/sandalskikyo_1_zip)
[Xevian's Spell System](https://anonfiles.com/xeFfs3ofz5/XevianSpellSystem_v1_2_unitypackage)
[Face Tracking for Anagura Work's Lesser Mokuri Body](https://store.vket.com/en/items/6614)
[Marshmallow PB (Ver1.3)](https://pixeldrain.com/u/7FzM38iE) Old version
[Marshmallow PB - ver1.5.1](https://workupload.com/file/sMgRRzZyNjM) Old version

### Textures:
[Body brush for Kikyo](https://anonfiles.com/Ndh8waq6zc/Kikyo_Body_Blush_R15_1_zip)
[Neko Eye texture - For Maya](https://linkmix.co/16318868) AnonFiles in LinkMix, the other URL works
[mariel Nine Tale texture](https://workupload.com/file/MjcnfQJPB3J)

### Shaders
[Motchiri Shader (ver.1.6.1)](https://pixeldrain.com/u/8e968sh8) multiple versions on site already exist anyways

Note: anything that was hosted on [anonfiles](https://anonfiles.com/) is now broken due to the site shutting down, i hope you can find some new URLs for them @vrchivejson

**Comment by TekkyNeko** [comment]
On another note, if one of us wants to provide any assets not on the site, how can we do that?

**Comment by Nommiiee** [comment]
I will be replacing the site completely. With better security, proper database and an integrated upload tool. I am fixing some final minutes issues related to the server. It would be hopefully done by the end of week.

**Comment by TekkyNeko** [comment]
alright sounds good 👍

**Comment by lilium-ux** [comment]
Some links have been re-uploaded.
### **Avatars:**

[Mariel - ver1.41](https://workupload.com/file/yTh3xrJCHCA)
[ALT chan](https://pixeldrain.com/u/Ft56ptwY)
[Kirche](https://workupload.com/file/aZFgJVXky9m)
[Aoi-chan](https://workupload.com/file/YHCDvCstJ4q)
[HPT-HASP2 "LINA"](https://pixeldrain.com/u/zsVNSouk)
[Moko v1.1](https://pixeldrain.com/u/RZSipSK3)
[Akio&Ruka 1.1](https://linkmix.co/18452376)
[Platinum_v1.2.2](https://workupload.com/file/tYeMAbnXSzm)
[Muromu](https://linkmix.co/18459549)
[Emmelie (v1.2)](https://workupload.com/archive/vLrUuGKd)

### **Clothing:**

[Outing bear-chan outfit](https://workupload.com/archive/24aRMxaQt3)
[Wrap Coat for TRESHA](https://pixeldrain.com/u/V6cBiuci)
[CusUniWear For Kikyo](https://pixeldrain.com/u/XQEnE4Fx)
[[Grus] Overall](hhttps://workupload.com/file/EzvbNgKm6wv)
[Jianshi Style_Selestia](https://workupload.com/file/2uf4wk3jvN8)
[Lily Cafe](https://workupload.com/file/Ncq4q2eneCW)
[Puff sleeves & Tulip skirt for Selestia](https://workupload.com/file/76U2eThuXNj)
[Leather Costume](https://workupload.com/file/PmqZHBgfVGP)
[Clothes that you don't have to think about anymore "Extension to wear"](https://workupload.com/file/qV7WNvWyWvR)
[Flower Dress](https://workupload.com/file/bEEPmA2z4C2)
[Night witch for kikyo](https://workupload.com/file/TEfuVwvcWfY)

[Slave＆Cute](https://workupload.com/file/hGXauJbERR2)
[Quack Quack Hike](https://workupload.com/file/2nPeLr63BwM)
[Chuchu dress](https://workupload.com/archive/Wey2AANag4) - Moe & Lime
[Urban Tech Obsidian for Lime](https://pixeldrain.com/l/iBRGX1yg)

**Comment by TekkyNeko** [comment]
removed those from the list, will probably close this once the new site goes up

**Comment by lilium-ux** [comment]
re-uploaded.
[suzuhana](https://drive.google.com/file/d/1d4G8t3mM1TF7b3_5MZWHRXbwcOSQVE0-/view?usp=sharing) - [Suzuhana v2.22](https://linkmix.co/18452269) works fine

[Runa Lazy Devil Set](https://pixeldrain.com/u/PYHsdLRj)
